import { useEffect, useState } from 'react';
import { useTaskStore } from '../store/useTaskStore';
import { Coffee, Play } from 'lucide-react';

export function ShortBreakOverlay() {
  const { breakEndTime, endBreak } = useTaskStore();
  const [timeLeft, setTimeLeft] = useState<number>(0);

  useEffect(() => {
    if (!breakEndTime) return;

    const updateTimer = () => {
      const remaining = Math.max(0, breakEndTime - Date.now());
      setTimeLeft(remaining);
      
      if (remaining === 0) {
        endBreak(); // Auto end when timer reaches 0
      }
    };

    updateTimer();
    const interval = setInterval(updateTimer, 1000);
    
    return () => clearInterval(interval);
  }, [breakEndTime, endBreak]);

  if (!breakEndTime || timeLeft <= 0) return null;

  const minutes = Math.floor(timeLeft / 60000);
  const seconds = Math.floor((timeLeft % 60000) / 1000);

  const timeString = `${minutes.toString().padStart(2, '0')}:${seconds.toString().padStart(2, '0')}`;

  const SARCASTIC_MESSAGES = [
    "Step away from the screen. Let your subconscious do what your conscious clearly won't.",
    "Another break? Bold move for someone with a task list that long.",
    "Three breaks today. Are we doing Pomodoro, or just 'avoiding work' with extra steps?",
    "Four breaks. I'm starting to think 'Focus' was an ironic name choice.",
    "Taking a break from what, exactly? Staring at the task form?",
    "Statistically, you're now spending more time resting than working. Congrats.",
    "If you take one more break, I'm going to start questioning your employment status.",
    "Your coffee must be getting lonely. It's been refilled three times today.",
    "A productivity app just watched you take your seventh break. Reflect on that.",
    "The tasks aren't going anywhere. Unfortunately, neither are you.",
    "Break number eight. At this rate, the tasks will outlive us both.",
    "You're either very disciplined with breaks or very undisciplined with work. Hard to tell.",
    "Your desk chair has seen more action than your task list today.",
    "Studies show breaks improve focus. This many breaks just improve your Netflix queue.",
    "Taking a break is healthy. This frequency is a personality trait.",
    "Your tasks are starting to think you've forgotten about them. They're fine. Probably.",
    "Another break. Your subconscious must be very well-rested by now.",
    "The Pomodoro method has work in it. You're doing all tomatoes, no pasta.",
    "At this pace, you'll finish that task sometime next fiscal year.",
    "Your future self is going to have *thoughts* about today's break count.",
    "Resting is productive. Sure. That's the hill we're dying on today.",
    "The cursor on that task hasn't moved in a while. Coincidence?",
    "You know what's a great break activity? Doing the task. Wild idea.",
    "Your productivity tracker would like to have a word with you. It's upset.",
    "Break time! Again. As always. As is tradition.",
    "Somewhere, a deadline is quietly laughing.",
    "Your keyboard is collecting dust at an impressive rate.",
    "Your tasks have filed a missing persons report. For you.",
    "The app is judging you silently. Well, not silently. Very loudly.",
    "You've mastered the art of strategic avoidance. An underrated skill, honestly.",
    "Another break. The tasks remain. The irony deepens.",
    "Your energy levels must be fascinating — always too low to work, always enough to rest.",
    "Historians will note you took many breaks before the big breakthrough. Probably.",
    "Every great thinker took breaks. None of them took this many before 2pm.",
    "If 'resting' were a task, you'd be done for the week.",
    "The break timer started. Your task list sighed audibly.",
    "At some point, the break *is* the work. You haven't reached that point.",
    "Your coworkers are wondering where you've been. So are your tasks.",
    "This is a mental reset. Your mental must be *very* reset by now.",
    "Your brain cells are so rested they've started their own vacation.",
    "Break champion. Gold medal. No tasks completed, but incredible resting form.",
    "You're not procrastinating. You're just 'pre-working.' Aggressively.",
    "The tasks are still there. They've been reading your browser history while you were gone.",
    "If breaks were deliverables, you'd be ahead of schedule.",
    "Your focus is like a browser tab — refreshed often, rarely productive.",
    "You could've finished that task in the time you've spent looking at this timer.",
    "Mental health matters. But so does that deadline from two weeks ago.",
    "Your break game is elite. Your shipping game is... developing.",
    "By now your chair indentation is permanent. That's legacy.",
    "Another one. Keep going. The tasks are immortal anyway.",
    "You pause work like it owes you money.",
    "Returning to work? No rush. The chaos will wait.",
    "Your task list has given up hope. It's journaling now.",
    "Time check: more breaks than tasks completed. This is fine.",
    "Somewhere a standup update is getting harder to write.",
    "You call it a break. Your manager calls it a mystery.",
    "The only thing consistent today is your break schedule.",
    "Zero tasks done, but your resting heart rate is immaculate.",
    "At this rate, 'done' is a concept for future you.",
    "Not judging. Just logging. (We're judging.)",
    "Your laptop fan has stopped trying. It gave up before you did.",
    "Every time you rest, a deadline gets its wings. And teeth.",
    "This app has watched you take breaks like a disappointed parent.",
    "Your tasks have moved through the stages of grief. They're at acceptance.",
    "The calendar says it's a workday. You've made it a philosophical one.",
    "Another break well earned by... existing, apparently.",
    "Your productivity score is negative. That's actually impressive.",
    "Break timer started. Task timer: still at zero. Checks out.",
    "You break more than government infrastructure.",
    "Your subconscious has processed so much it started a podcast.",
    "The 'sarcastic break messages' feature was built for you, wasn't it.",
    "You've out-broken your own record. A legend in your time.",
    "Focus is a muscle. Yours is currently on sabbatical.",
    "Your task list has started rooting for you ironically.",
    "The break timer is the only thing you've seen to completion today.",
    "Another beautiful break in a long series of beautiful breaks.",
    "If 'stepping away' burned calories, you'd be in incredible shape.",
    "Your attention span and your task list haven't met in a while.",
    "Deep work requires deep rest, apparently. All day rest.",
    "The coffee is cold. The tasks are warm. The irony is perfect.",
    "Your work-to-break ratio would make an economist cry.",
    "Yet another break. Your keyboard misses you. Not really, but still.",
    "At this point, calling it a 'break' is generous. This is a lifestyle.",
    "Your next action was logged. It's still logged. Patiently waiting.",
    "The app is professionally concerned.",
    "You've taken so many breaks the timer has started sighing.",
    "Every break is a fresh start. You're very fresh.",
    "Your task list has its own therapy session scheduled.",
    "More breaks than git commits. Not ideal.",
    "Time to rest from the rest you just had. Classic.",
    "Your inbox unread count is growing in real time. Enjoy the break.",
    "Another opportunity to not do the thing.",
    "At some point this becomes a meditation practice. You're not there yet.",
    "Your energy bar depletes only during work hours. Remarkable.",
    "Resting like it's going out of style. Spoiler: it's not.",
    "Your task queue is a time capsule at this point.",
    "You break at the drop of a hat. The hat has been dropped many times.",
    "The only sprint happening here is to the coffee machine.",
    "You could've shipped a feature. Instead: vibes.",
    "Your calendar says 'focus block.' Your behavior says 'focus blur.'",
    "No judgment. Just a quiet observation that nothing has been done.",
    "Another peaceful moment while the backlog grows sentient.",
    "Your break count is approaching philosophical levels.",
    "The app has started taking notes on your behavior. For science.",
    "If breaks were deployments, you'd be running continuous delivery.",
    "Your resting face is getting a lot of practice.",
    "Deep breath. The tasks aren't going anywhere. Sadly.",
    "One hundred breaks in and going strong. Strong at resting.",
    "You're getting your masters in stopping. Summa cum laude.",
    "Your tasks have started a support group. Attendance is high.",
    "Another break. The world turns. The backlog grows.",
    "You rest like someone who has never met a deadline.",
    "Your brain is so well-rested it's started questioning reality.",
    "This break was earned by the last break, which was earned by the one before.",
    "The 'resume work' button is starting to feel abandoned.",
    "Your laptop screen is getting more breaks than you are.",
    "At some point, this becomes a data point in a case study.",
    "Your daily break count is a personal best. Every single day.",
    "Taking a break before the work starts — a bold strategy.",
    "The task said 'next action.' Apparently the next action is this. Again.",
    "If someone tracked your breaks, they'd submit a thesis.",
    "Every break is a small act of rebellion against the backlog.",
    "Your subconscious is probably done. Your work is not.",
    "Another quality break. Excellent form. No notes. Many tasks.",
    "Break culture is real and you are its ambassador.",
    "Your rest is unmatched. Your output is... also unmatched.",
    "The deadline is a social construct. The break timer is not.",
    "Resting is an art form. You are its unsung master.",
    "Somewhere, a product manager is refreshing Jira.",
    "Your focus sessions are shorter than your break sessions. Coincidence.",
    "Your task list is a fossil at this point. Carbon-dating in progress.",
    "You've unlocked a new achievement: 'Consistent Inconsistency.'",
    "Another break. Another moment where work didn't happen.",
    "The app salutes your commitment to not committing.",
    "You rest with the dedication others reserve for shipping.",
    "If 'taking five' were billable, you'd be rich.",
    "Break loading… break loaded. Work: still queued.",
    "Your task titles have started to blur together from neglect.",
    "At this cadence, retirement looks like your current schedule.",
    "The break timer ends. The hesitation begins.",
    "Your next action is sitting there, blinking, questioning its purpose.",
    "Every minute of break is a minute of tasks not done. Math is brutal.",
    "This break sponsored by procrastination and poor planning.",
    "Your keyboard is developing abandonment issues.",
    "Back for another break. The loyalty is admirable, if misplaced.",
    "Your resting game has surpassed your working game. Trophy pending.",
    "The tasks have scheduled a meeting. You're not invited.",
    "Another break. You are hydrated, rested, and behind schedule.",
    "Your work/life balance is mostly life, mostly rest, very little work.",
    "This is fine. Everything is fine. The backlog is fine.",
    "The only delivery happening today is your coffee order.",
    "Your future self is drafting a strongly worded letter.",
    "Your tasks are writing their memoirs. The title is 'Waiting.'",
    "Focus: missing. Last seen: two weeks ago.",
    "Your break list is longer than your done list. By a lot.",
    "The next sprint starts with you, eventually, maybe, returning to work.",
    "Your brain cells are on a group vacation. Destination: not work.",
    "Another tactical pause in a day full of tactical pauses.",
    "You're not avoiding work. You're giving work time to mature.",
    "Your deadline just set its own deadline. For you.",
    "Resting harder than you've worked all day. A masterclass.",
    "Your task list says 'active.' Your behavior says 'passive.'",
    "The break timer is the most reliable thing in your workflow.",
    "Your hustle is a myth. Your rest is very, very real.",
    "Another one. The count climbs. The work waits.",
    "You take breaks like someone who's never had consequences.",
    "Your task board is a historical archive. Curators are interested.",
    "One more break closer to the end of the day. That's one strategy.",
    "Your rest streak is undefeated.",
    "Productivity is a spectrum and you are at one end of it.",
    "If breaks were features, you'd have shipped a lot today.",
    "The timer ticks. The tasks sit. The irony compounds.",
    "Your working memory isn't getting much practice today.",
    "Legendary break count. Zero legendary task completions.",
    "You have mastered the pause. The play button is gathering dust.",
    "The app is beginning to think you're testing the break feature.",
    "Another break in a sequence of breaks that would impress a mathematician.",
    "Your task count is unchanged. Your break count is not.",
    "This break was inevitable. The next one will be too.",
    "Your flow state is a myth told to frighten junior developers.",
    "Another break. The project timeline weeps quietly.",
    "You are in the zone. The zone is not work.",
    "Your productivity graph looks like a flatline with occasional spikes of breaks.",
    "The backlog has evolved. Grown legs. Started a family. You have not.",
    "Your tasks are filing for independence.",
    "You rest with the confidence of someone who has everything under control. Interesting.",
    "Another pause. The cursor blinks. Nothing changes.",
    "Your task list has started accepting its fate.",
    "Work is a concept. Breaks are a practice. You practice a lot.",
    "If your break count were a KPI, you'd be employee of the month.",
    "Deep focus requires deep breaks, apparently. Very deep.",
    "Your future self will handle it. Your future self is not happy about this.",
    "The break is over when you say it is. You haven't said it yet.",
    "Another moment of 'rest' in a day of 'rest.'",
    "Your keyboard has started writing tasks itself. Out of spite.",
    "You break like the simulation needs you to break.",
    "This break count is historical. In the wrong direction.",
    "The tasks have given you a nickname. It's not flattering.",
    "You are resting your way through the workday. Efficiently.",
    "Another break. Another missed sprint goal. Another day.",
    "Your focus window is permanently minimized.",
    "Resting at this frequency should be studied. Academically.",
    "Your task list has more items than your break list has logic.",
    "You're building toward something. Probably not the tasks.",
    "The app is running out of sympathy. And messages. Almost.",
    "Another break. The deadline calendar has gone red.",
    "You could run a marathon in the time you've spent not working.",
    "Your current output: vibes, mostly. Some regret.",
    "The backlog is geological now. Layers upon layers of deferred intent.",
    "Your tasks are archived. Not by you. By time.",
    "If there were a break world record, you'd hold it. Twice.",
    "Your rest is impressive. Your output is not.",
    "The next action on your task says 'do the thing.' You have not done the thing.",
    "Another lap around the break track. Personal best.",
    "Your inbox and your task list are collaborating against you.",
    "You have transcended work-life balance. You are only life.",
    "The tasks are vintage. Aged to perfection. Still not done.",
    "Your subconscious is overqualified and underutilized.",
    "Another moment of mandatory reflection. Reflect on the tasks.",
    "You've broken more than ground today.",
    "Your task board is a museum exhibit titled 'Things Not Done.'",
    "The break timer ends. The stalling begins.",
    "You'd be unstoppable if you started.",
    "Another break claimed by the champion of not shipping.",
    "Your rest is immaculate. Your velocity is not.",
    "The deadline is a legend now. A myth passed down through sprints.",
    "If commitment were currency, yours is spent on breaks.",
    "Your 'current focus' should really be renamed 'current avoidance.'",
    "The app is running a simulation of what your output could've been. It's better.",
    "Another break. The code untouched. The timer tireless.",
    "Your to-do list has started a revolution. You're not the leader.",
    "You take breaks like someone who invented them.",
    "The project is behind. The breaks are on schedule.",
    "Your tasks have achieved enlightenment waiting for you.",
    "Another tactical retreat from productivity.",
    "Your rest game has a better win rate than your work game.",
    "The timer knows your routine better than your routine does.",
    "You've rested enough to power a small country. The tasks remain.",
    "Your 'deep work' is very deep. Beneath the surface. Buried.",
    "Another break. Somewhere, an engineer is shipping your feature for you.",
    "Your breaks are consistent. Your work is a mystery.",
    "You are a case study in scheduled avoidance. The researchers are baffled.",
    "Your productivity would be legendary if it existed.",
    "Another moment of strategic non-action.",
    "The timer has more discipline than you do. It always ends on time.",
    "Your task list ages like fine wine. You're the one who let it sit.",
    "Another break. The cursor blinks. The tasks age.",
    "You rest like the work will do itself. Spoiler: it won't.",
    "Your backlog is a time capsule. Future archaeologists will have questions.",
    "The only consistent thing today: the breaks.",
    "Your future self sent a message. It said 'why.'",
    "Another break earned by taking the last break.",
    "You could have shipped it. You chose serenity. Respect, mostly.",
    "Your task list has a therapist now.",
    "The app is quietly impressed by your commitment to rest.",
    "You're in uncharted productivity territory. Specifically, the void.",
    "Your rest is aspirational. Your task list is aspirational too. In a bad way.",
    "Another moment where work was possible and breaks were chosen.",
    "You break with the precision of someone who planned it. You didn't.",
    "Your output is minimal. Your break output is record-breaking.",
    "The timer started. The tasks waited. As always.",
    "This break cadence is your legacy. Adjust accordingly.",
    "Your velocity graph is a horizontal line at zero. Elegant.",
    "Another break in the books. The books are full of breaks.",
    "You've rested more than you've worked. That's a choice.",
    "Your task list filed a complaint. The app is reviewing it.",
    "Another moment of reflection. Please reflect on the tasks.",
    "The code compiles itself out of pity. You're welcome.",
    "Your rest has outlasted every deadline this week.",
    "Another break. The work is patient. The deadline is not.",
    "If breaks were features, you'd have shipped a product.",
    "Your task status: queued. Your break status: legendary.",
    "The app has seen things. Mostly you taking breaks.",
    "Your backlog has a backlog. It's recursive. Like your avoidance.",
    "Another strategic pause in a day of strategic pauses.",
    "You rest with the energy others spend finishing things.",
    "Your focus has left the building. It didn't leave a note.",
    "Another break. Another unit of time that could've been work.",
    "Your sprint velocity is negative. Technically impressive.",
    "The tasks have stopped expecting you. They've found peace.",
    "Another moment where the timer counted down and work did not begin.",
    "You've built a break habit that would make a sloth nervous.",
    "Your next break is already loading. Be honest — you know it.",
    "You absolute legend of resting. The backlog remains unimpressed.",
    "Another one for the books. The books are full of breaks.",
    "You deserve this break. The tasks don't agree, but here we are.",
    "Your ability to rest is truly a gift. To yourself. Not to your tasks.",
    "The 'resume work' button has filed for emotional support.",
    "Your task list has started learning a new language. It has time.",
    "If avoidance were an Olympic sport, you'd be on the podium.",
    "Another break. The standups write themselves. Poorly.",
    "Your keyboard is cleaner than your conscience right now.",
    "You've achieved rest levels previously only documented in hibernation studies.",
    "The backlog has a backlog. You know this. You continue.",
    "Your mouse hasn't moved productively in hours. It's fine. It's not.",
    "Another break. Somewhere, a Gantt chart is crying.",
    "You rest like deadlines are a rumor someone told you once.",
    "Your task list sent a postcard. It misses you.",
    "The sprint ended. The tasks did not.",
    "You're not behind. You're just aggressively ahead of next week's problems.",
    "Another break. The cursor blinks. The world spins. Nothing ships.",
    "Your daily schedule is 10% work, 90% 'one more minute.'",
    "If breaks were commits, your repo would be full.",
    "Your future self just opened this app and sighed heavily.",
    "The tasks are patient. The deadline is not. Guess which one wins.",
    "Another break. The feature branch grows stale.",
    "You are the human embodiment of a loading spinner.",
    "Your output today: zero tasks, infinite breaks, one very confused app.",
    "The only merge happening today is you merging with your chair.",
    "Your code isn't writing itself. We checked.",
    "Another break taken with the confidence of someone who finished everything. You didn't.",
    "Your task list is so old it has its own lore now.",
    "A watched pot never boils. An unwatched task never ships.",
    "Your breaks are legendary. Your pull requests are folklore.",
    "The app has started a support group for your tasks. It's oversubscribed.",
    "Another break. Another story you'll tell about how busy you were.",
    "Your workflow is just: break, break, break, panic, break.",
    "You rest with the serenity of someone who doesn't check Slack.",
    "The sprint is over. The work isn't. The breaks are plentiful.",
    "Your velocity this week can be described as 'ambient.'",
    "Another break. The technical debt compounds interest daily.",
    "You're not procrastinating, you're letting ideas breathe. For hours.",
    "Your focus would be impressive if it were pointed at anything.",
    "The deadline passed you like a car on a highway. You waved.",
    "Another one. The app is running out of ways to say 'really?'",
    "Your break schedule is the only thing running on time today.",
    "The project manager sent a ping. You're on break. Again.",
    "Your task completion rate rounds down to zero. Consistently.",
    "Another break, another story about how you 'almost' started.",
    "You've spent more time reading sarcastic messages than writing code.",
    "Your flow state has been missing since Tuesday.",
    "The break ends. The hesitation begins. Classic.",
    "You are one with the chair. The chair has more commits.",
    "Another break. The roadmap weeps quietly in the corner.",
    "Your task list is now categorized under 'historical documents.'",
    "You've out-waited your own deadline. An achievement, technically.",
    "The app logs your breaks for posterity. Posterity is appalled.",
    "Another moment where nothing happened and you called it self-care.",
    "Your team is shipping. You are sipping. Balance.",
    "The tasks have unionized. They want better treatment. Or any treatment.",
    "Another break. Your IDE has gone to sleep. It gave up first.",
    "You rest with the energy of someone who finished their work. You haven't.",
    "Your break count has its own line item in the project budget.",
    "The app tried to suggest a task. You clicked away. Several times.",
    "Another break. The codebase is aging like milk in the sun.",
    "Your current status: resting. Your required status: working. Gap: enormous.",
    "The timer ends and you take a moment to consider taking another break.",
    "Your next action requires action. That's the whole problem.",
    "Another break well executed. The tasks remain poorly executed.",
    "You have a gift for pausing. A talent, really. Wasted, but still.",
    "The task list isn't getting shorter on its own. Trust us, we checked.",
    "Another break. The scope creeps. The work sleeps.",
    "Your resting is impressive. Your shipping is theoretical.",
    "You've taken so many breaks, the app now expects them.",
    "Another moment of strategic inaction in a field of possible action.",
    "Your keyboard has logged zero keystrokes in the last hour. It's concerned.",
    "The break bar is full. The progress bar is not.",
    "Another break. You remain. The tasks remain. The irony persists.",
    "Your to-do list is a time machine to last week's ambitions.",
    "The standup will be brief tomorrow. 'What did you do? Breaks. Just breaks.'",
    "Another break. The bug isn't fixing itself. We checked.",
    "You rest like the code will refactor itself. It won't.",
    "Your sprint points this week: negative vibes.",
    "The backlog grows with every break. You've contributed significantly.",
    "Another break. The product is patient. The users are not.",
    "Your WIP limit is zero. Your break limit is apparently infinite.",
    "The task queue is not a suggestion. But you've made it one.",
    "Another break. Your commit history for today: nothing.",
    "You are in deep rest. The work requires deep work. Unfortunate.",
    "Your tasks have aged into a vintage problem set.",
    "Another break. The PR sits unreviewed. By you. Of course.",
    "You rest like the retrospective will sort everything out.",
    "Your velocity has been redefined as 'philosophical zero.'",
    "Another break. The CI pipeline has more activity than you.",
    "Your calendar blocked 'focus time.' Your behavior blocked the work.",
    "The app can't help but notice the pattern here.",
    "Another break. The issue tracker is lonely.",
    "You've rested enough to solve world hunger. The tasks remain.",
    "Your 'in progress' column is a lie and you know it.",
    "Another break. The deployment waits. The environment idles.",
    "You treat breaks like they're free. Spoiler: they cost time.",
    "Your feature is almost done. Has been almost done. For days.",
    "Another break. The test suite is green. Your output is not.",
    "You rest like someone who has read all the productivity books but skipped chapter one.",
    "Your next action: do the next action. Revolutionary insight.",
    "Another break. The user story has no ending yet.",
    "You are very good at stopping. Less good at starting.",
    "Your task timer is at zero. Your break timer is a champion.",
    "Another break. Your backlog is now a palimpsest.",
    "You've been 'almost ready to start' for a measurable amount of time.",
    "The app has started predicting your break times. It's never wrong.",
    "Another break. The sprint velocity is a math problem you're avoiding.",
    "Your task: queued. Your state: also queued.",
    "The only thing you've completed today is this sentence. And the breaks.",
    "Another break. The Kanban board is stuck. Literally.",
    "You rest with the discipline of someone who has already shipped. You haven't.",
    "Your productivity is playing the long game. Very long.",
    "Another break. The feature flag is off. So is your engine.",
    "You've broken the record for most breaks without a corresponding output.",
    "The review process has been waiting for you. So has the work.",
    "Another break. The database schema is unchanged. So is your task count.",
    "Your output today is best described as 'ambient effort.'",
    "The app has filed a report: breaks up, output down, everything expected.",
    "Another break. The cache is warm. The tasks are cold.",
    "You rest like your IDE won't be covered in red squiggles when you return.",
    "Your sprint has more breaks than a Kit Kat commercial.",
    "Another break. The client is waiting. The work is waiting. You are resting.",
    "You're not burned out. You're pre-emptively recovering.",
    "Your todo list could be a museum exhibit: 'Things Deferred.'",
    "Another break. The architecture decision hasn't been made. By you.",
    "You rest with the consistency that your code lacks.",
    "Your tasks are queued with the patience of monks.",
    "Another break. The integration test is red. You are resting.",
    "Your focus is between tasks. Specifically, in the space between tasks. Always.",
    "The break counter has become the most meaningful metric in your day.",
    "Another break. The README doesn't update itself. We know you know.",
    "You've been 'wrapping up' since 10am.",
    "The tasks asked about you. We said you'd be back soon. We were wrong.",
    "Another break. The logs are clean. Your conscience is not.",
    "Your mental bandwidth is fully allocated to resting.",
    "The done column is sparse. The break column is thriving.",
    "Another break. The UX hasn't been tested. By anyone. Including you.",
    "You rest while the bugs reproduce unmolested.",
    "Your throughput is negative. Mathematically interesting.",
    "Another break. The delivery date slides by one more day.",
    "You are very committed to this process. Wrong process, but very committed.",
    "Your work-in-progress hasn't progressed. Irony noted.",
    "Another break. The requirements doc grows longer without you.",
    "You rest like every problem solves itself given enough time.",
    "Your 'current focus' is on not focusing. Meta.",
    "Another break. The queue grows. The throughput stagnates.",
    "You take breaks with such precision that it almost looks intentional.",
    "Your task board is a monument to optimism.",
    "Another break. The feedback hasn't been actioned. You've been actioning breaks.",
    "You rest at a rate that exceeds your iteration speed.",
    "Your retro action items from last month are still open.",
    "Another break. The hotfix can wait. Apparently.",
    "You are clearly built for endurance. Endurance resting.",
    "Your idea is great. The implementation is theoretical.",
    "Another break. The product demo is tomorrow. The work is today. You are here.",
    "You rest like tomorrow is guaranteed to be productive. Bold.",
    "Your efficiency rating: art project.",
    "Another break. The database query is still slow. You are slower.",
    "You have a remarkable talent for making this look like a system.",
    "Your scope didn't creep. Your breaks did.",
    "Another break. The roadmap says 'Q2.' You say 'Q-whenever-I-get-to-it.'",
    "You treat tasks like wine — better after some time. Except they're not wine.",
    "Your break cadence is more consistent than your deploy cadence.",
    "Another break. The user is waiting. The task is waiting. The break is not waiting.",
    "You rest like every deadline is aspirational.",
    "Your tech debt is compounding. You are decompressing.",
    "Another break. The error boundary caught an exception. You're the exception.",
    "You've achieved a state of perfect stillness in a moving project.",
    "Your sprint isn't agile. It's stationary.",
    "Another break. The estimations were wrong. Your break count was not.",
    "You rest like the QA team will catch everything anyway.",
    "Your release notes for today would be blank.",
    "Another break. The infrastructure is idle. So are you. At least you match.",
    "You're taking a break from a break. Nested breaks. Recursion.",
    "Your task list has started sending you motivational quotes. Desperately.",
    "Another break. The milestone is missed. The break is hit.",
    "You rest with the confidence of someone on a well-deserved vacation. This is Tuesday.",
    "Your 10x output is coming. Just after this break. And the next.",
    "Another break. The environment is stable. Your progress is not.",
    "You have broken so many breaks that breaks have broken.",
    "Your contribution to the project today: presence. Debatable presence.",
    "Another break. The API is rate-limiting your output. So are you.",
    "You rest like you're sponsored by a mattress company.",
    "Your pull request needs one more review. From you. When you return.",
    "Another break. The server is up. Your productivity is not.",
    "You are in flow. Specifically, the flow of taking breaks.",
    "Your task completion rate would make a loading bar embarrassed.",
    "Another break. The sprint board looks the same as this morning. Exactly.",
    "You rest like someone who has already earned it. The math disagrees.",
  ];



  const getSarcasticMessage = () => {
    const idx = Math.floor(Math.random() * SARCASTIC_MESSAGES.length);
    return SARCASTIC_MESSAGES[idx];
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-[#0f1115]/95 backdrop-blur-xl animate-in fade-in duration-500">
      <div className="flex flex-col items-center max-w-md w-full px-6">
        <div className="w-20 h-20 bg-slate-800 rounded-full flex items-center justify-center mb-8 relative">
          <div className="absolute inset-0 rounded-full border-4 border-slate-700"></div>
          <svg className="absolute inset-0 transform -rotate-90" viewBox="0 0 100 100">
            <circle
              cx="50"
              cy="50"
              r="48"
              fill="transparent"
              stroke="var(--color-accent)"
              strokeWidth="4"
              strokeDasharray="301.59"
              strokeDashoffset={301.59 * (1 - timeLeft / (5 * 60000))} // Defaulting scale to 5 min for visual effect, rough approx
              className="transition-all duration-1000 linear"
            />
          </svg>
          <Coffee size={32} className="text-slate-300 relative z-10" />
        </div>
        
        <h2 className="text-2xl font-bold text-white mb-2">Mental Reset</h2>
        <p className="text-slate-400 text-center mb-8">
          {getSarcasticMessage()}
        </p>

        <div className="text-6xl font-mono font-bold text-white mb-12 tracking-tighter">
          {timeString}
        </div>

        <button
          onClick={endBreak}
          className="flex items-center gap-2 px-6 py-3 bg-slate-800 hover:bg-slate-700 text-slate-200 rounded-xl font-medium transition-all hover:scale-105 active:scale-95"
        >
          <Play size={18} /> Resume Work Early
        </button>
      </div>
    </div>
  );
}
